# LINEAR ALGEBRA

In [4]:
import numpy as np
import pandas as pd

In [5]:
vector = np.arange(5)
print(vector)

[0 1 2 3 4]


In [6]:
matrix=np.arange(24).reshape(6,4)
print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [7]:
tips=pd.read_csv('tips.csv')
tips.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15,Sun2251


In [8]:
tips.values # values will convert a dataframe to a numpy array

array([[16.99, 1.01, 'Female', ..., 'Christy Cunningham',
        3560330000000000.0, 'Sun2959'],
       [10.34, 1.66, 'Male', ..., 'Douglas Tucker', 4478070000000000.0,
        'Sun4608'],
       [21.01, 3.5, 'Male', ..., 'Travis Walters', 6011810000000000.0,
        'Sun4458'],
       ...,
       [22.67, 2.0, 'Male', ..., 'Keith Wong', 6011890000000000.0,
        'Sat3880'],
       [17.82, 1.75, 'Male', ..., 'Dennis Dixon', 4375220000000.0,
        'Sat17'],
       [18.78, 3.0, 'Female', ..., 'Michelle Hardin', 3511450000000000.0,
        'Thur672']], shape=(244, 11), dtype=object)

In [9]:
mat1=np.random.randint(10,51,size=(3,3,))
mat2=np.random.randint(50,100,size=(3,3,))

In [10]:
mat1

array([[31, 15, 47],
       [43, 23, 23],
       [40, 11, 10]], dtype=int32)

In [11]:
mat2

array([[76, 67, 78],
       [63, 70, 91],
       [55, 92, 52]], dtype=int32)

In [12]:
#addition of matrices
mat1+mat2 #np.add(mat1,mat2)

array([[107,  82, 125],
       [106,  93, 114],
       [ 95, 103,  62]], dtype=int32)

mat1 + 10

***Subtraction of matrices***

In [13]:
mat1 - mat2

array([[-45, -52, -31],
       [-20, -47, -68],
       [-15, -81, -42]], dtype=int32)

In [14]:
mat2 -mat1

array([[45, 52, 31],
       [20, 47, 68],
       [15, 81, 42]], dtype=int32)

***Division of matrices***

In [15]:
mat1/mat2 # actually it will not happen like that it works as - mat1 @ inverse of mat2

array([[0.40789474, 0.2238806 , 0.6025641 ],
       [0.68253968, 0.32857143, 0.25274725],
       [0.72727273, 0.11956522, 0.19230769]])

note- matrices have to be the same shapes to perform operation on them (same rows and columns)

***Element wise multiplication or hadamard product***

In [16]:
mat1 * mat2

array([[2356, 1005, 3666],
       [2709, 1610, 2093],
       [2200, 1012,  520]], dtype=int32)

***Actual matrix multiplication or dot product***

In [17]:
mat1 @ mat2 #np.dot(mat1,mat2)

array([[5886, 7451, 6227],
       [5982, 6607, 6643],
       [4283, 4370, 4641]], dtype=int32)

In [18]:
mat1

array([[31, 15, 47],
       [43, 23, 23],
       [40, 11, 10]], dtype=int32)

***Transpose of matrix***

In [19]:
mat1.T

array([[31, 43, 40],
       [15, 23, 11],
       [47, 23, 10]], dtype=int32)

***Rank of matrices*** 

how many rows and columns are unique.

allow us to find duplicate columns and rows

help us to identify duplicate or redundant data

***reddundant info*** - if one row is the multiple of another row .like mat=[[123][369]] and we will remove this redundant row and then there would
be only one row left then it will be considered as 1st rank .

***eg*** - i you get your salary as two columns like in inr or dollar dont you think we need both as instead of this having one column we can find another

***rank*** - how many rows or columns are unique 
rank of matrix (row wise) = rank of matrix (column wise)
if rank of matrix is 200 it mean only these are useful other than these are useless

***Additive Prop*** -as having additive prop ,lwt say in this if two rows r1 and r2 are unique and r3 is the addition of elements of r1 and r2 (additive prop ) , same follow as in column wise then we can state that r3  and c3 is useless and rank would be 2 (r1 ,r2 or c1,c2)

***Eg*** - if i give you length,width and area of the house do you really need area column of the house as instead you can also find the area
by your own having length and breadth , so giving area is useless.

In [20]:
np.linalg.matrix_rank(mat1)

np.int64(3)

***Determinant of a matrix*** - whether a matrix is single or not
note - if there is any matrix whose determinant is 0 we cant calculate is inverse.

In [21]:
np.linalg.det(mat1)

np.float64(-14372.000000000018)

In [22]:
mat3=np.arange(9).reshape(3,3)

In [23]:
mat3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

***logic behind function of numpy***

numpy is a package within this there are small small files called module and all of these python files have pre written functions and classes

one such python file is linalg.py and within that there is a function called matrix_rank . eg - np.linalg.matrix_rank()

***Inverse***
if the determinant of  a mtrix is 0 then we cant calculate its inverse other than this we can find inverse .

like A = A^-1(inverse of A) or 1/A

***To check whether the inv of matrix is correct or not***

if we A*1/A(inv) we got I (identity matrix).

for no 8 *1/8 we got 1 (unit no )(identity matrix).

In [24]:
np.linalg.det(mat3)

np.float64(0.0)

In [25]:
mat1_inv=np.linalg.inv(mat1)

In [26]:
np.linalg.inv(mat3)

LinAlgError: Singular matrix

In [ ]:
# check whether the inverse is correct or not 
mat1_inv @ mat1 # here we got the identity matrix diagonally diagonal are one and 0 everywhere

In [ ]:
np.round((mat1_inv @ mat1),2) # to see identity matrix properly by rounding off

# LINEAR ALGEBRA HANDSON

In [27]:
#create a 3*3 matrix(3 rows and 3 columns)
#add 50 to your matrix
#subtract 20 from your matrix
#multiply 3 in your matrix
#divide your matrix by 4

In [30]:
mat=np.random.randint(10,50,size=(3,3))
mat

array([[17, 13, 24],
       [34, 44, 49],
       [34, 38, 40]], dtype=int32)

In [31]:
print(mat+50)
print(mat-20)
print(mat*3)
print(mat/4)

[[67 63 74]
 [84 94 99]
 [84 88 90]]
[[-3 -7  4]
 [14 24 29]
 [14 18 20]]
[[ 51  39  72]
 [102 132 147]
 [102 114 120]]
[[ 4.25  3.25  6.  ]
 [ 8.5  11.   12.25]
 [ 8.5   9.5  10.  ]]


In [32]:
#perform the dot product btw two matrix of size (2,2)

In [37]:
mat1=np.random.randint(10,50,size=(2,2))
mat2=np.random.randint(10,50,size=(2,2))
# two ways to perform dot product
print(mat1@mat2)
print(np.dot(mat1,mat2))

[[ 739  820]
 [1504 1776]]
[[ 739  820]
 [1504 1776]]


In [50]:
# Property - transpose of a transposed gives the original matrix.

In [52]:
print("original matrix : \n",mat1)
t_mat=mat1.T
print("transposed matrix : \n",t_mat)
print("transpose of transposed matrix :\n",t_mat.T)

original matrix : 
 [[16 31]
 [45 43]]
transposed matrix : 
 [[16 45]
 [31 43]]
transpose of transposed matrix :
 [[16 31]
 [45 43]]


In [63]:
# property - additive property
#(a+b).T=a.T+b.T
#multiplicative property
#(a*b).T=(a.T)*(b.t)

In [74]:
# Create sample matrices
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Calculate sides
right_side = (a.T) + (b.T)
left_side = (a + b).T

# Check equality
print("Is (a+b).T == (a.T) + (b.T) equal : \n", np.array_equal(left_side, right_side))
# Output: True


Is (a+b).T == (a.T) + (b.T) equal : 
 True


In [78]:
# Create sample matrices
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Calculate sides for the correct identity (AB).T == B.T @ A.T
left_side = (a @ b).T
right_side = (b.T) @ (a.T) # Note the reversed order: b.T @ a.T

# Check equality
print("Is (a @ b).T == (b.T) @ (a.T) equal:", np.array_equal(left_side, right_side))


Is (a @ b).T == (b.T) @ (a.T) equal: True


In [79]:
# create a 3*3 matrix find determinant
# check is it invertible or singular


In [82]:
mat=np.random.randint(10,50,size=(3,3))
det=np.linalg.det(mat)
print(det)
if det==0:
    print("singluar")
else:
    print("inveritble")

35463.00000000004
inveritble


In [ ]:
#identity matrix

In [87]:
inv_a=np.linalg.inv(a)
if (a==inv_a).all():
    print("matrix is not inverse")
else:
    print("matrix is inverse")
    

matrix is inverse


In [88]:
# check for identity matrix property :

In [93]:
print(mat)
invm=np.linalg.inv(mat)
print(invm)
c= mat @ invm
print(c)
d=np.identity(3)
print(d)
if (c==d).all():
    print("identity matrix")
else:
    print(" not identity matrix")

[[12 25 40]
 [45 36 12]
 [22 42 13]]
[[-0.00101514  0.03820884 -0.03214618]
 [-0.00905169 -0.02041564  0.04669656]
 [ 0.03096185  0.00129713 -0.01954149]]
[[ 1.00000000e+00 -2.94902991e-17  1.11022302e-16]
 [-1.38777878e-17  1.00000000e+00 -1.94289029e-16]
 [ 1.73472348e-17 -7.30752264e-17  1.00000000e+00]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 not identity matrix


In [94]:
#practice exercise
#calculating rank of a matrix
#caluculating eigen value and eigen vector